### ISSUE TITLE
Invalid WarpedMinecraftDecoder parameters

### ISSUE THREAD

**Issue by flori-schwa** [WolverinDEV/BungeeUtil#48]
```
17:17:37 [SCHWERWIEGEND] Invalid WarpedMinecraftDecoder parameters! Cant having an client without a handshake but with a version!
17:17:37 [SCHWERWIEGEND] Invalid WarpedMinecraftDecoder parameters! Cant having an client without a handshake but with a version!
```

BungeeUtil Version: 2.5.4
BungeeCord version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:a1f9c2e:1258
Error occurs: On Server Ping / When connecting
Bungeecord running on Windows 10 without any extra JVM parameters

Bungeecord config.yml:

```
ip_forward: true
network_compression_threshold: 256
stats: 68c31828-9826-4ded-ae44-c6fc83fd0c9a
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```

BungeeUtil config.yml:

```
# 
#              Timings:                # 
#         Loging timings on/off        # 
#                                      # 
#              Updater:                # 
#           Enable outo update         # 
#                                      # 
#             ByteBuffType:            # 
#  The Used Buffer type for Packets    # 
#              Avariable:              # 
#    - 'direct'                        # 
#    - 'heap'                          # 
#                                      # 
#               Terminal:              # 
#      Colors in terminal on/off       # 
#                                      # 
#            Async-Catcher:            # 
#  Enable it for more packet security  # 
#        The catcher has 2 modes:      # 
# - EXCEPTION (will throw a exception) # 
# - WARNING (will print a warn message)# 
#                                      #
#             Debug messages           #
#   Enable/Disable all debug messages  #  
#                                      # 
#               Utils:                 # 
#  Enable/Disable some unused feature  #  
#             to save ram              #  
#                                      # 
#                                      # 
#        Handle Exception Action:      # 
#        DISCONNECT, PRINT, NONE       #  
timings: true
updater: true
byteBuffType: direct
system:
  gc:
    enabled: false
    periode: 60000
terminal:
  colored: true
debug:
  ram-statistics: true
  messages: true
loading:
  inject:
    buffer-size: 65536
  fastboot: false
  quiet: false
async-catcher:
  enabled: true
  mode: EXCEPTION
inventory:
  synchandle: true
utils:
  scoreboard: true
  bossbar: true
network:
  exception: DISCONNECT
lastVersion: 2.5.4
```

https://github.com/WolverinDEV/BungeeUtil/blob/f033564da9d9b6055b3c13d87d2ecc9c5cfb5195/src/main/java/dev/wolveringer/bungeeutil/netty/WarpedMinecraftDecoder.java#L82
